using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

// Import the ExampleLibrary.dll. Generated by compiling 'ExampleLibrary.cs'.
using ExampleLibrary;

namespace LocalProgram
{
    class LocalProgram
    {
        static void Main()
        {
            // Will be used to define number of iterations
            int iterations = 3;

            // Define type of result variable
            int result;

            // Do 3 iterations
            for (int i = 0; i < iterations; i++)
            {
                // Create new class instance with desired input arguments
                LibraryDist ld = new LibraryDist(i);

                // Call the execute method that calls the 'Sum' method defined in 'ExampleLibrary.dll'
                result = ld.Execute();

                // Print the result to the standard out stream
                System.Console.WriteLine("Result of iteration {0}: {1}", i + 1, result);
            }
        }
    }

    class LibraryDist // Class containing some executable code
    {

        // Define type of variables that will be used
        int Iteration;
        int Result;

        // Define constructor that takes one input argument
        public LibraryDist(int iteration)
        {
            this.Iteration = iteration;
        }

        // Define an 'Execute' method containing the code that will be executed
        public int Execute()
        {
            // Call the 'Sum' method defined in 'ExampleLibrary.dll'.
            Result = SumClass.Sum(Iteration, Iteration);

            // Return the result of the summation
            return (Result);

        }

    }

}
